channels:
  - damianavila82
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - bokeh
  - rise
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - nbpresent
